library(sqldf)
data <- read.csv.sql('./data/household_power_consumption.txt',"select * from file where Date in ('1/2/2007','2/2/2007')", sep = ';', header = T)
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data$DateTime <- paste(data$Date, data$Time)
data$DateTime <- strptime(data$DateTime, format = "%Y-%m-%d %H:%M:%S")
plot(data$DateTime, data$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab= "")
lines(data$DateTime, data$Sub_metering_2, col = "red", type = "l", xlab= "")
lines(data$DateTime, data$Sub_metering_3, col = "blue", type = "l", xlab= "")
legend("topright", col = c("black", "red", "blue"), lty = c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "Plot3.png")
dev.off()