data5rows <- read.table("./data/household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", nrows = 5)
classes <- sapply(data5rows, class)
library(data.table)
data <- fread("./data/household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", colClasses = classes)
data$Date <- as.Date(data$Date, "%d/%m/%Y")
library(dplyr)
sub_data <- filter(data, Date == "2007-02-01" | Date == "2007-02-02")
hist(as.numeric(sub_data$Global_active_power), main = "Global active power", col = "red", xlab = "Global active power (kilowatts)")
dev.copy(png, "Plot 1.png")
dev.off()